import Head from 'next/head'

export default function HeadDefault() {
  return (
    <Head>
      <title>Harry Potter</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/harryFavicon.png" />
    </Head>
  )
}